#!/usr/bin/env python3
"""Generate the transient CPU-boost MachineConfig.

  python3 -I make-boost-machineconfig.py --role master --enabled true \
      --max-platform-cpus 32 > 99-platform-cpu-boost.yaml

--enabled false installs the script and unit but leaves the unit disabled,
which is how you take a clean baseline boot before enabling the boost: both
boots then carry identical files and only the unit state differs.

--max-platform-cpus caps the boosted set. Do not exceed 32: Go sizes
GOMAXPROCS from the CPU count visible at process start, and above ~32 its
memory management makes throughput go DOWN, not up. Processes that are
already running keep their original GOMAXPROCS when widened (Go reads
affinity once at startup), so the cap only matters for anything that restarts
during the boost -- but that is exactly what happens during boot.

--exclude-cpus is the hard guarantee for interrupt-sensitive Guaranteed
dataplane pods: those CPUs are never used by the boost even if the CPU
Manager has not yet claimed them.
"""
import argparse
import base64
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
ap = argparse.ArgumentParser()
ap.add_argument("--role", default="master")
ap.add_argument("--enabled", default="true", choices=["true", "false"])
ap.add_argument("--max-platform-cpus", default="32")
ap.add_argument("--poll-sec", default="2")
ap.add_argument("--max-boost-sec", default="1800")
ap.add_argument("--exclude-cpus", default="")
ap.add_argument("--runq-wait-us", default="150")
a = ap.parse_args()

if int(a.max_platform_cpus) > 32:
    raise SystemExit("refusing: --max-platform-cpus > 32 (Go GOMAXPROCS cliff)")

ENVFILE = f"""# Generated -- consumed by platform-cpu-boost.service.
# Cap on the boosted platform set. Above ~32 Go's GOMAXPROCS scaling makes
# throughput worse, not better.
MAX_PLATFORM_CPUS={a.max_platform_cpus}
# How often to re-read kubelet's CPU Manager state. This is the window in
# which a newly admitted Guaranteed dataplane pod could briefly share a CPU
# with platform work, so lower is safer.
POLL_SEC={a.poll_sec}
# Hard ceiling on the boost window regardless of convergence.
MAX_BOOST_SEC={a.max_boost_sec}
# CPUs the boost must never use, even when unclaimed. Set this to the cpuset
# your latency-sensitive dataplane pods will be given.
EXCLUDE_CPUS={a.exclude_cpus}
# Convergence threshold: mean run-queue wait on the reserved CPUs, in us.
# NOT cpu.pressure -- PSI is unavailable by default on 4.20 and 4.22.
RUNQ_WAIT_US={a.runq_wait_us}
STABLE_CHECKS=5
CHECK_EVERY=15
# How long to wait for kubelet to write cpu_manager_state. After=kubelet
# only means kubelet exec'd, not that it has initialised the CPU Manager.
STATE_WAIT_SEC=120
"""


def b64(data):
    if isinstance(data, str):
        data = data.encode()
    return "data:text/plain;charset=utf-8;base64," + base64.b64encode(data).decode()


def ind(text, n):
    pad = " " * n
    return "\n".join(pad + ln if ln else "" for ln in text.splitlines())


script = b64((HERE / "platform-cpu-boost.sh").read_bytes())
envf = b64(ENVFILE)
unit = (HERE / "platform-cpu-boost.service").read_text()

print(f"""---
# Generated by make-boost-machineconfig.py -- edit the sources in
# deliverables/tuning/ and regenerate.
#
# Temporarily widens the CPU affinity of the control plane onto idle isolated
# CPUs during the boot window, then narrows back on convergence.
#
# Does NOT change reservedSystemCPUs: node allocatable and the CPU Manager
# state file are untouched, so no Guaranteed pod is restarted.
# Does NOT touch ovs-vswitchd/ovsdb-server: on 4.21.z+ ovn-kubernetes manages
# those dynamically via the kubelet PodResource API, and interfering
# wedges ovsdb.
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-{a.role}-platform-cpu-boost
  labels:
    machineconfiguration.openshift.io/role: {a.role}
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
        - path: /usr/local/bin/platform-cpu-boost.sh
          mode: 0755
          overwrite: true
          contents:
            source: {script}
        - path: /etc/sysconfig/platform-cpu-boost
          mode: 0644
          overwrite: true
          contents:
            source: {envf}
    systemd:
      units:
        - name: platform-cpu-boost.service
          enabled: {a.enabled}
          contents: |
{ind(unit, 12)}""")
