#!/usr/bin/env python3
"""Generate the boot-perf MachineConfig from the plain files in this directory.

Keeping the collector as a real script (rather than hand-maintained base64
inside YAML) means it stays editable and reviewable. Re-run this after any
edit to boot-perf-collect.sh.

  python3 -I make-machineconfig.py > 99-boot-perf-collector.yaml
  oc apply -f 99-boot-perf-collector.yaml
"""
import base64
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROLE = sys.argv[1] if len(sys.argv) > 1 else "master"


def inline(path):
    b = (HERE / path).read_bytes()
    return "data:text/plain;charset=utf-8;base64," + base64.b64encode(b).decode()


def unit(name):
    body = (HERE / name).read_text()
    return name, body


script = inline("boot-perf-collect.sh")
svc_name, svc_body = unit("boot-perf-collect.service")
slice_name, slice_body = unit("boot-perf.slice")


def indent(text, n):
    pad = " " * n
    return "\n".join(pad + line if line else "" for line in text.splitlines())


print(f"""---
# Generated by make-machineconfig.py -- do not edit inline; edit the source
# files in deliverables/collector/ and regenerate.
#
# Installs an early-boot performance collector that starts before crio and
# kubelet and runs off the reserved CPU set.
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-{ROLE}-boot-perf-collector
  labels:
    machineconfiguration.openshift.io/role: {ROLE}
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
        - path: /usr/local/bin/boot-perf-collect.sh
          mode: 0755
          overwrite: true
          contents:
            source: {script}
    systemd:
      units:
        - name: {slice_name}
          enabled: false
          contents: |
{indent(slice_body, 12)}
        - name: {svc_name}
          enabled: true
          contents: |
{indent(svc_body, 12)}""")
